[project]
name = "gs2gs"
version = "0.1.0"

dependencies = [
    "nerfstudio>=1.1.5",
]

[tool.setuptools.packages.find]
include = ["gs2gs"]

[project.entry-points.'nerfstudio.method_configs']
gs2gs = 'gs2gs.gs2gs_config:gs2gs'